<?php

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_58861a3b6e8d0',
	'title' => 'Quotes',
	'fields' => array (
		array (
			'placement' => 'top',
			'endpoint' => 0,
			'key' => 'field_588769846a43d',
			'label' => 'Infield Skin Area',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'post_type' => array (
				0 => 'materials',
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'object',
			'ui' => 1,
			'key' => 'field_58861d455d0f5',
			'label' => '1. Select the finishing layer material for the infield skin.',
			'name' => 'marco_infield_skin_materials',
			'type' => 'post_object',
			'instructions' => 'Please select a material type to use on the field',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'layout' => 'horizontal',
			'choices' => array (
				'Yes' => 'Yes',
				'No' => 'No',
			),
			'default_value' => '',
			'other_choice' => 0,
			'save_other_choice' => 0,
			'allow_null' => 1,
			'return_format' => 'value',
			'key' => 'field_58861edad05bd',
			'label' => '2. Grass infield?',
			'name' => 'marco_infield_skin_grass_infield',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'layout' => 'horizontal',
			'choices' => array (
				'Yes' => 'Yes',
				'No' => 'No',
			),
			'default_value' => '',
			'other_choice' => 0,
			'save_other_choice' => 0,
			'allow_null' => 1,
			'return_format' => 'value',
			'key' => 'field_588621a5c305c',
			'label' => '3. Grass sidelines?',
			'name' => 'marco_infield_skin_grass_sidelines',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'message' => '',
			'esc_html' => 0,
			'new_lines' => 'wpautop',
			'key' => 'field_588622701b41f',
			'label' => '4. Enter the following measurements:',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_58862395c5ec8',
			'label' => 'Radius: (feet)',
			'name' => 'marco_infield_skin_radius_feet',
			'type' => 'number',
			'instructions' => 'Distance from front/centre pitching rubber to infield',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_58866266c9fe7',
			'label' => 'Base Path Width: (feet)',
			'name' => 'marco_infield_skin_base_path_width_feet',
			'type' => 'number',
			'instructions' => 'Width of Base line (if required)',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_58861edad05bd',
						'operator' => '==',
						'value' => '',
					),
				),
				array (
					array (
						'field' => 'field_58861edad05bd',
						'operator' => '==',
						'value' => 'Yes',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_588662a0c9fe8',
			'label' => 'Sidelines Length: (feet)',
			'name' => 'marco_infield_skin_sidelines_length_feet',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_588621a5c305c',
						'operator' => '==',
						'value' => '',
					),
				),
				array (
					array (
						'field' => 'field_588621a5c305c',
						'operator' => '==',
						'value' => 'No',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_588662c1c9fe9',
			'label' => 'Sidelines Width: (feet)',
			'name' => 'maco_infield_skin_sidelines_width_feet',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_588621a5c305c',
						'operator' => '==',
						'value' => '',
					),
				),
				array (
					array (
						'field' => 'field_588621a5c305c',
						'operator' => '==',
						'value' => 'No',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_58866231c9fe6',
			'label' => 'Base Length: (feet)',
			'name' => 'marco_infield_skin_base_length_feet',
			'type' => 'number',
			'instructions' => 'Distance from Home Plate to 1st Base',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_588662e5c9fea',
			'label' => 'Depth of Finishing Layer Material: (inches)',
			'name' => 'marco_infiedl_skin_depth_of_finishing_layer_material_inches',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'post_type' => array (
				0 => 'materials',
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'object',
			'ui' => 1,
			'key' => 'field_588663c4045b2',
			'label' => '5. Select the base layer material for the infield skin.',
			'name' => 'marco_infield_skin_base_layer',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_588664ce045b3',
			'label' => 'Depth of Base Layer Material: (inches)',
			'name' => 'marco_infield_skin_base_material_depth_of_base_layer_material_inches',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'placement' => 'top',
			'endpoint' => 0,
			'key' => 'field_58876b1c6a43e',
			'label' => 'Pitchers Mound Area',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'layout' => 'vertical',
			'choices' => array (
				'standard' => 'Standard (Complete)',
				'cap_construction' => 'Cap Construction (Partial)',
				'bricks_only_construction' => 'Bricks Only Construction (Partial)',
				'softball_pitchers_pad' => 'Softball Pitcher\'s Pad',
			),
			'default_value' => '',
			'other_choice' => 0,
			'save_other_choice' => 0,
			'allow_null' => 1,
			'return_format' => 'value',
			'key' => 'field_58866ae4c6d89',
			'label' => '1. Select a Mound Construction Method',
			'name' => 'marco_pitchers_mound_select_a_mound_construction_method',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'post_type' => array (
				0 => 'materials',
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'object',
			'ui' => 1,
			'key' => 'field_58876de972b6d',
			'label' => '2. Select the finishing layer material for the pitchers mound.',
			'name' => 'marco_pitchers_mound_materials',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'layout' => 'horizontal',
			'choices' => array (
				'bagged' => 'Bagged',
				'in_bulk' => 'In Bulk',
			),
			'default_value' => '',
			'other_choice' => 0,
			'save_other_choice' => 0,
			'allow_null' => 0,
			'return_format' => 'value',
			'key' => 'field_58876e2672b6e',
			'label' => 'Materials Packaging',
			'name' => 'marco_pitchers_mound_materials_packaging',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'layout' => 'horizontal',
			'choices' => array (
				'yes' => 'Yes',
				'no' => 'No',
			),
			'default_value' => '',
			'other_choice' => 0,
			'save_other_choice' => 0,
			'allow_null' => 1,
			'return_format' => 'value',
			'key' => 'field_58876ea572b6f',
			'label' => 'Use Field Bricks?',
			'name' => 'marco_pitchers_mound_use_field_bricks',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_58866ae4c6d89',
						'operator' => '==',
						'value' => 'standard',
					),
				),
				array (
					array (
						'field' => 'field_58866ae4c6d89',
						'operator' => '==',
						'value' => 'cap_construction',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'layout' => 'vertical',
			'choices' => array (
				'standard' => 'Standard',
				'expanded' => 'Expanded',
			),
			'default_value' => '',
			'other_choice' => 0,
			'save_other_choice' => 0,
			'allow_null' => 1,
			'return_format' => 'value',
			'key' => 'field_58877159a5901',
			'label' => 'Select Brick Layout:',
			'name' => 'marco_pitchers_mound_select_brick_layout',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_58876ea572b6f',
						'operator' => '==',
						'value' => 'yes',
					),
				),
				array (
					array (
						'field' => 'field_58866ae4c6d89',
						'operator' => '==',
						'value' => 'bricks_only_construction',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'message' => '',
			'esc_html' => 0,
			'new_lines' => 'wpautop',
			'key' => 'field_5887738793e1e',
			'label' => '3. Enter the following measurements:',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_58866ae4c6d89',
						'operator' => '==',
						'value' => 'standard',
					),
				),
				array (
					array (
						'field' => 'field_58866ae4c6d89',
						'operator' => '==',
						'value' => 'cap_construction',
					),
				),
				array (
					array (
						'field' => 'field_58866ae4c6d89',
						'operator' => '==',
						'value' => 'bricks_only_construction',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_588773ab93e1f',
			'label' => 'Mound Radius: (feet)',
			'name' => 'marco_pitchers_mount_mound_radius_feet',
			'type' => 'number',
			'instructions' => 'Distance from centre point to edge of mound circle',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_58866ae4c6d89',
						'operator' => '==',
						'value' => 'standard',
					),
				),
				array (
					array (
						'field' => 'field_58866ae4c6d89',
						'operator' => '==',
						'value' => 'cap_construction',
					),
				),
				array (
					array (
						'field' => 'field_58866ae4c6d89',
						'operator' => '==',
						'value' => 'bricks_only_construction',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_588773d693e20',
			'label' => 'Pitching Rubber Height: (inches)',
			'name' => 'marco_pitchers_mound_pitching_rubber_height_inches',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_58866ae4c6d89',
						'operator' => '==',
						'value' => 'standard',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_5887745193e23',
			'label' => 'Depth of Mound Cap: (inches)',
			'name' => 'marco_pitchers_mound_depth_of_mound_cap_inches',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_58866ae4c6d89',
						'operator' => '==',
						'value' => 'cap_construction',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'post_type' => array (
				0 => 'materials',
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'object',
			'ui' => 1,
			'key' => 'field_5887758a85e94',
			'label' => '4. Select the base layer material for the pitchers mound.',
			'name' => 'marco_pitchers_mound_second_material',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_588775b385e95',
			'label' => 'Depth of Base Layer Material: (inches)',
			'name' => 'marco_pitchers_mound_depth_of_base_layer_material_inches',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'placement' => 'top',
			'endpoint' => 0,
			'key' => 'field_5887762b4eb2c',
			'label' => 'Home Plate Area',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'post_type' => array (
				0 => 'materials',
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'object',
			'ui' => 1,
			'key' => 'field_58877728009e5',
			'label' => '1. Select the finishing layer material for the home plate area.',
			'name' => 'marco_home_plate_material',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_5887781b82cef',
			'label' => '2. Home Plate Radius: (feet)',
			'name' => 'marco_home_plate_home_plate_radius_feet',
			'type' => 'number',
			'instructions' => 'Distance from back point of Home Plate to grass edge',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_5887784182cf0',
			'label' => 'Depth of Home Plate Materials: (inches)',
			'name' => 'marco_home_plate_depth_of_home_plate_materials_inches',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'layout' => 'vertical',
			'choices' => array (
				'none' => 'None',
				'3_x_5' => '3\' x 5\'',
				'4_x_6' => '4\' x 6\'',
			),
			'default_value' => '',
			'other_choice' => 0,
			'save_other_choice' => 0,
			'allow_null' => 0,
			'return_format' => 'value',
			'key' => 'field_5887792582cf1',
			'label' => '3. Batters Boxes?',
			'name' => 'marco_home_plate_batters_boxes',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'post_type' => array (
				0 => 'materials',
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'object',
			'ui' => 1,
			'key' => 'field_58877ca925b3b',
			'label' => 'Select the finishing layer material for the Batters Boxes.',
			'name' => 'marco_home_plate_select_the_finishing_layer_material_for_the_batters_boxes',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_5887792582cf1',
						'operator' => '==',
						'value' => '3_x_5',
					),
				),
				array (
					array (
						'field' => 'field_5887792582cf1',
						'operator' => '==',
						'value' => '4_x_6',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'layout' => 'vertical',
			'choices' => array (
				'bagged' => 'Bagged',
				'in_bulk' => 'In Bulk',
			),
			'default_value' => '',
			'other_choice' => 0,
			'save_other_choice' => 0,
			'allow_null' => 0,
			'return_format' => 'value',
			'key' => 'field_58877cc625b3c',
			'label' => 'Materials Packaging Type',
			'name' => 'marco_home_plate_batters_box_materials_packaging_type',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_5887792582cf1',
						'operator' => '==',
						'value' => '3_x_5',
					),
				),
				array (
					array (
						'field' => 'field_5887792582cf1',
						'operator' => '==',
						'value' => '4_x_6',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'layout' => 'vertical',
			'choices' => array (
				'yes' => 'Yes',
				'no' => 'No',
			),
			'default_value' => '',
			'other_choice' => 0,
			'save_other_choice' => 0,
			'allow_null' => 0,
			'return_format' => 'value',
			'key' => 'field_58877d0425b3d',
			'label' => 'Use Field Bricks?',
			'name' => 'marco_home_plate_batters_box_use_field_bricks',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_5887792582cf1',
						'operator' => '==',
						'value' => '3_x_5',
					),
				),
				array (
					array (
						'field' => 'field_5887792582cf1',
						'operator' => '==',
						'value' => '4_x_6',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'layout' => 'vertical',
			'choices' => array (
				'none' => 'None',
				'3_x_5' => '3\' x 5\'',
				'4_x_6' => '4\' x 6\'',
			),
			'default_value' => '',
			'other_choice' => 0,
			'save_other_choice' => 0,
			'allow_null' => 0,
			'return_format' => 'value',
			'key' => 'field_5887813a4f360',
			'label' => '4. Catchers Box?',
			'name' => 'marco_home_plate_catcher_box',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'post_type' => array (
				0 => 'materials',
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'object',
			'ui' => 1,
			'key' => 'field_588781204f35f',
			'label' => 'Select the finishing layer material for the Catchers Box',
			'name' => 'macro_home_plate_select_the_finishing_layer_material_for_the_catchers_box',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_5887813a4f360',
						'operator' => '==',
						'value' => '3_x_5',
					),
				),
				array (
					array (
						'field' => 'field_5887813a4f360',
						'operator' => '==',
						'value' => '4_x_6',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'layout' => 'vertical',
			'choices' => array (
				'bagged' => 'Bagged',
				'in_bulk' => 'In Bulk',
			),
			'default_value' => '',
			'other_choice' => 0,
			'save_other_choice' => 0,
			'allow_null' => 0,
			'return_format' => 'value',
			'key' => 'field_588782675558e',
			'label' => 'Materials Packaging Type',
			'name' => 'marco_home_plate_catchers_box_materials_packaging_type',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_5887813a4f360',
						'operator' => '==',
						'value' => '3_x_5',
					),
				),
				array (
					array (
						'field' => 'field_5887813a4f360',
						'operator' => '==',
						'value' => '4_x_6',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'layout' => 'vertical',
			'choices' => array (
				'yes' => 'Yes',
				'no' => 'No',
			),
			'default_value' => '',
			'other_choice' => 0,
			'save_other_choice' => 0,
			'allow_null' => 0,
			'return_format' => 'value',
			'key' => 'field_588782805558f',
			'label' => 'Use Field Bricks?',
			'name' => 'marco_home_plate_catchers_box_use_field_bricks',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_5887813a4f360',
						'operator' => '==',
						'value' => '3_x_5',
					),
				),
				array (
					array (
						'field' => 'field_5887813a4f360',
						'operator' => '==',
						'value' => '4_x_6',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'post_type' => array (
				0 => 'materials',
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'object',
			'ui' => 1,
			'key' => 'field_588782c255590',
			'label' => '5. Select the base layer material for the home plate area.',
			'name' => 'marco_home_plate_select_the_base_layer_material_for_the_home_plate_area',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_5887830db01b8',
			'label' => 'Depth of Base Layer Material: (inches)',
			'name' => 'marco_home_plate_depth_of_base_layer_second_material_inches',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'placement' => 'top',
			'endpoint' => 0,
			'key' => 'field_588784442ff9b',
			'label' => 'Warning Track Area',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'post_type' => array (
				0 => 'materials',
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'object',
			'ui' => 1,
			'key' => 'field_5887844e2ff9c',
			'label' => '1. Select the material for the warning track.',
			'name' => 'marco_warning_track_select_the_material_for_the_warning_track',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'message' => '',
			'esc_html' => 0,
			'new_lines' => 'wpautop',
			'key' => 'field_588784752ff9d',
			'label' => '2. Enter the following measurements:',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_588784992ff9e',
			'label' => 'Perimeter: (feet)',
			'name' => 'marco_warning_track_perimeter_feet',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_588784b32ff9f',
			'label' => 'Width: (feet)',
			'name' => 'marco_warning_track_width_feet',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_588784c92ffa0',
			'label' => 'Depth of Warning Track Materials: (inches)',
			'name' => 'marco_warning_track_depth_of_warning_track_materials_inches',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'post_type' => array (
				0 => 'materials',
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'object',
			'ui' => 1,
			'key' => 'field_5887861e2ffa1',
			'label' => '3. Select the base layer material for the warning track.',
			'name' => 'marco_warning_track_select_the_base_layer_material_for_the_warning_track',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_588786462ffa2',
			'label' => 'Depth of Base Layer Material: (inches)',
			'name' => 'marco_warning_track_depth_of_base_layer_material_inches',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'placement' => 'top',
			'endpoint' => 0,
			'key' => 'field_588786682ffa3',
			'label' => 'Bull Pen Area',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'layout' => 'horizontal',
			'choices' => array (
				'1' => 'One Bull Pen',
				'2' => 'Two Bull Pens',
			),
			'default_value' => 'two_bull_pens',
			'other_choice' => 0,
			'save_other_choice' => 0,
			'allow_null' => 0,
			'return_format' => 'value',
			'key' => 'field_5887867c2ffa4',
			'label' => '1. Quantity',
			'name' => 'marco_bull_pen_quantity',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'post_type' => array (
				0 => 'materials',
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'object',
			'ui' => 1,
			'key' => 'field_588786e02ffa5',
			'label' => '2. Select the finishing layer material of the bull pen.',
			'name' => 'marco_bull_pen_select_the_finishing_layer_material_of_the_bull_pen',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'message' => '',
			'esc_html' => 0,
			'new_lines' => 'wpautop',
			'key' => 'field_588788c36f908',
			'label' => '3. Enter the following measurements:',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_588788db6f909',
			'label' => 'Length: (feet)',
			'name' => 'marco_bull_pen_length_feet',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_588788ea6f90a',
			'label' => 'Width: (feet)',
			'name' => 'marco_bull_pen_width_feet',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_588788ff6f90b',
			'label' => 'Depth of Materials: (inches)',
			'name' => 'marco_bull_pen_depth_of_materials_inches',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'post_type' => array (
				0 => 'materials',
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'object',
			'ui' => 1,
			'key' => 'field_5887891a6f90c',
			'label' => '4. Select the base layer material for the bull pen.',
			'name' => 'marco_bull_pen_select_the_base_layer_material_for_the_bull_pen',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_588789316f90d',
			'label' => 'Depth of Base Layer Material: (inches)',
			'name' => 'marco_bull_pen_depth_of_base_layer_material_inches',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'placement' => 'top',
			'endpoint' => 0,
			'key' => 'field_58878b83a1347',
			'label' => 'Miscellaneous Area',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_58878b90a1348',
			'label' => '1. Enter a name for this area.',
			'name' => 'marco_miscellaneous_enter_a_name_for_this_area',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'layout' => 'vertical',
			'choices' => array (
				'one_area' => 'One Area',
				'two_of_these_areas' => 'Two of these Areas',
			),
			'default_value' => '',
			'other_choice' => 0,
			'save_other_choice' => 0,
			'allow_null' => 0,
			'return_format' => 'value',
			'key' => 'field_58878ba5a1349',
			'label' => '2. Quantity',
			'name' => 'marco_miscellaneous_quantity',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'post_type' => array (
				0 => 'materials',
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'object',
			'ui' => 1,
			'key' => 'field_58878bdea134a',
			'label' => '3. Select the finishing layer material',
			'name' => 'marco_miscellaneous_select_the_finishing_layer_material',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'layout' => 'vertical',
			'choices' => array (
				'dimensions' => 'Dimensions',
				'area' => 'Area (sq. ft)',
			),
			'default_value' => '',
			'other_choice' => 0,
			'save_other_choice' => 0,
			'allow_null' => 0,
			'return_format' => 'value',
			'key' => 'field_58878c3aa695a',
			'label' => '4. Enter the following measurements:',
			'name' => 'marco_miscellaneous_enter_the_following_measurements:',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_58878c72a695b',
			'label' => 'Length: (feet)',
			'name' => 'marco_miscellaneous_length_feet',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_58878c3aa695a',
						'operator' => '==',
						'value' => 'dimensions',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_58878c98a695c',
			'label' => 'Width: (feet)',
			'name' => 'marco_miscellaneous_width_feet',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_58878c3aa695a',
						'operator' => '==',
						'value' => 'dimensions',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_58878caba695d',
			'label' => 'Area: (sq. ft)',
			'name' => 'marco_miscellaneous_area',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_58878c3aa695a',
						'operator' => '==',
						'value' => 'area',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_58878d48a695e',
			'label' => 'Depth of Materials: (inches)',
			'name' => 'marco_miscellaneous_depth_of_materials_inches',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'post_type' => array (
				0 => 'materials',
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'object',
			'ui' => 1,
			'key' => 'field_58878d61a695f',
			'label' => '5. Select the base layer material.',
			'name' => 'marco_miscellaneous_select_the_base_layer_material',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_58878d9ba6960',
			'label' => 'Depth of Base Layer Material: (inches)',
			'name' => 'marco_miscellaneous_depth_of_base_layer_material_inches',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'quotes',
			)
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;


if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_58861a3b6e8d0',
	'title' => 'Quotes',
	'fields' => array (
		array (
			'placement' => 'top',
			'endpoint' => 0,
			'key' => 'field_588769846a43d',
			'label' => 'Infield Skin Area',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'post_type' => array (
				0 => 'materials',
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'object',
			'ui' => 1,
			'key' => 'field_58861d455d0f5',
			'label' => '1. Select the finishing layer material for the infield skin.',
			'name' => 'marco_infield_skin_materials',
			'type' => 'post_object',
			'instructions' => 'Please select a material type to use on the field',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'layout' => 'horizontal',
			'choices' => array (
				'Yes' => 'Yes',
				'No' => 'No',
			),
			'default_value' => '',
			'other_choice' => 0,
			'save_other_choice' => 0,
			'allow_null' => 1,
			'return_format' => 'value',
			'key' => 'field_58861edad05bd',
			'label' => '2. Grass infield?',
			'name' => 'marco_infield_skin_grass_infield',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'layout' => 'horizontal',
			'choices' => array (
				'Yes' => 'Yes',
				'No' => 'No',
			),
			'default_value' => '',
			'other_choice' => 0,
			'save_other_choice' => 0,
			'allow_null' => 1,
			'return_format' => 'value',
			'key' => 'field_588621a5c305c',
			'label' => '3. Grass sidelines?',
			'name' => 'marco_infield_skin_grass_sidelines',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'message' => '',
			'esc_html' => 0,
			'new_lines' => 'wpautop',
			'key' => 'field_588622701b41f',
			'label' => '4. Enter the following measurements:',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_58862395c5ec8',
			'label' => 'Radius: (feet)',
			'name' => 'marco_infield_skin_radius_feet',
			'type' => 'number',
			'instructions' => 'Distance from front/centre pitching rubber to infield',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_58866266c9fe7',
			'label' => 'Base Path Width: (feet)',
			'name' => 'marco_infield_skin_base_path_width_feet',
			'type' => 'number',
			'instructions' => 'Width of Base line (if required)',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_58861edad05bd',
						'operator' => '==',
						'value' => '',
					),
				),
				array (
					array (
						'field' => 'field_58861edad05bd',
						'operator' => '==',
						'value' => 'Yes',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_588662a0c9fe8',
			'label' => 'Sidelines Length: (feet)',
			'name' => 'marco_infield_skin_sidelines_length_feet',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_588621a5c305c',
						'operator' => '==',
						'value' => '',
					),
				),
				array (
					array (
						'field' => 'field_588621a5c305c',
						'operator' => '==',
						'value' => 'No',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_588662c1c9fe9',
			'label' => 'Sidelines Width: (feet)',
			'name' => 'maco_infield_skin_sidelines_width_feet',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_588621a5c305c',
						'operator' => '==',
						'value' => '',
					),
				),
				array (
					array (
						'field' => 'field_588621a5c305c',
						'operator' => '==',
						'value' => 'No',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_58866231c9fe6',
			'label' => 'Base Length: (feet)',
			'name' => 'marco_infield_skin_base_length_feet',
			'type' => 'number',
			'instructions' => 'Distance from Home Plate to 1st Base',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_588662e5c9fea',
			'label' => 'Depth of Finishing Layer Material: (inches)',
			'name' => 'marco_infiedl_skin_depth_of_finishing_layer_material_inches',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'post_type' => array (
				0 => 'materials',
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'object',
			'ui' => 1,
			'key' => 'field_588663c4045b2',
			'label' => '5. Select the base layer material for the infield skin.',
			'name' => 'marco_infield_skin_base_layer',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_588664ce045b3',
			'label' => 'Depth of Base Layer Material: (inches)',
			'name' => 'marco_infield_skin_base_material_depth_of_base_layer_material_inches',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'placement' => 'top',
			'endpoint' => 0,
			'key' => 'field_58876b1c6a43e',
			'label' => 'Pitchers Mound Area',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'layout' => 'vertical',
			'choices' => array (
				'standard' => 'Standard (Complete)',
				'cap_construction' => 'Cap Construction (Partial)',
				'bricks_only_construction' => 'Bricks Only Construction (Partial)',
				'softball_pitchers_pad' => 'Softball Pitcher\'s Pad',
			),
			'default_value' => '',
			'other_choice' => 0,
			'save_other_choice' => 0,
			'allow_null' => 1,
			'return_format' => 'value',
			'key' => 'field_58866ae4c6d89',
			'label' => '1. Select a Mound Construction Method',
			'name' => 'marco_pitchers_mound_select_a_mound_construction_method',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'post_type' => array (
				0 => 'materials',
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'object',
			'ui' => 1,
			'key' => 'field_58876de972b6d',
			'label' => '2. Select the finishing layer material for the pitchers mound.',
			'name' => 'marco_pitchers_mound_materials',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'layout' => 'horizontal',
			'choices' => array (
				'bagged' => 'Bagged',
				'in_bulk' => 'In Bulk',
			),
			'default_value' => '',
			'other_choice' => 0,
			'save_other_choice' => 0,
			'allow_null' => 0,
			'return_format' => 'value',
			'key' => 'field_58876e2672b6e',
			'label' => 'Materials Packaging',
			'name' => 'marco_pitchers_mound_materials_packaging',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'layout' => 'horizontal',
			'choices' => array (
				'yes' => 'Yes',
				'no' => 'No',
			),
			'default_value' => '',
			'other_choice' => 0,
			'save_other_choice' => 0,
			'allow_null' => 1,
			'return_format' => 'value',
			'key' => 'field_58876ea572b6f',
			'label' => 'Use Field Bricks?',
			'name' => 'marco_pitchers_mound_use_field_bricks',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_58866ae4c6d89',
						'operator' => '==',
						'value' => 'standard',
					),
				),
				array (
					array (
						'field' => 'field_58866ae4c6d89',
						'operator' => '==',
						'value' => 'cap_construction',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'layout' => 'vertical',
			'choices' => array (
				'standard' => 'Standard',
				'expanded' => 'Expanded',
			),
			'default_value' => '',
			'other_choice' => 0,
			'save_other_choice' => 0,
			'allow_null' => 1,
			'return_format' => 'value',
			'key' => 'field_58877159a5901',
			'label' => 'Select Brick Layout:',
			'name' => 'marco_pitchers_mound_select_brick_layout',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_58876ea572b6f',
						'operator' => '==',
						'value' => 'yes',
					),
				),
				array (
					array (
						'field' => 'field_58866ae4c6d89',
						'operator' => '==',
						'value' => 'bricks_only_construction',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'message' => '',
			'esc_html' => 0,
			'new_lines' => 'wpautop',
			'key' => 'field_5887738793e1e',
			'label' => '3. Enter the following measurements:',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_58866ae4c6d89',
						'operator' => '==',
						'value' => 'standard',
					),
				),
				array (
					array (
						'field' => 'field_58866ae4c6d89',
						'operator' => '==',
						'value' => 'cap_construction',
					),
				),
				array (
					array (
						'field' => 'field_58866ae4c6d89',
						'operator' => '==',
						'value' => 'bricks_only_construction',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_588773ab93e1f',
			'label' => 'Mound Radius: (feet)',
			'name' => 'marco_pitchers_mount_mound_radius_feet',
			'type' => 'number',
			'instructions' => 'Distance from centre point to edge of mound circle',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_58866ae4c6d89',
						'operator' => '==',
						'value' => 'standard',
					),
				),
				array (
					array (
						'field' => 'field_58866ae4c6d89',
						'operator' => '==',
						'value' => 'cap_construction',
					),
				),
				array (
					array (
						'field' => 'field_58866ae4c6d89',
						'operator' => '==',
						'value' => 'bricks_only_construction',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_588773d693e20',
			'label' => 'Pitching Rubber Height: (inches)',
			'name' => 'marco_pitchers_mound_pitching_rubber_height_inches',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_58866ae4c6d89',
						'operator' => '==',
						'value' => 'standard',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_5887745193e23',
			'label' => 'Depth of Mound Cap: (inches)',
			'name' => 'marco_pitchers_mound_depth_of_mound_cap_inches',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_58866ae4c6d89',
						'operator' => '==',
						'value' => 'cap_construction',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'post_type' => array (
				0 => 'materials',
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'object',
			'ui' => 1,
			'key' => 'field_5887758a85e94',
			'label' => '4. Select the base layer material for the pitchers mound.',
			'name' => 'marco_pitchers_mound_second_material',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_588775b385e95',
			'label' => 'Depth of Base Layer Material: (inches)',
			'name' => 'marco_pitchers_mound_depth_of_base_layer_material_inches',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'placement' => 'top',
			'endpoint' => 0,
			'key' => 'field_5887762b4eb2c',
			'label' => 'Home Plate Area',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'post_type' => array (
				0 => 'materials',
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'object',
			'ui' => 1,
			'key' => 'field_58877728009e5',
			'label' => '1. Select the finishing layer material for the home plate area.',
			'name' => 'marco_home_plate_material',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_5887781b82cef',
			'label' => '2. Home Plate Radius: (feet)',
			'name' => 'marco_home_plate_home_plate_radius_feet',
			'type' => 'number',
			'instructions' => 'Distance from back point of Home Plate to grass edge',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_5887784182cf0',
			'label' => 'Depth of Home Plate Materials: (inches)',
			'name' => 'marco_home_plate_depth_of_home_plate_materials_inches',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'layout' => 'vertical',
			'choices' => array (
				'none' => 'None',
				'3_x_5' => '3\' x 5\'',
				'4_x_6' => '4\' x 6\'',
			),
			'default_value' => '',
			'other_choice' => 0,
			'save_other_choice' => 0,
			'allow_null' => 0,
			'return_format' => 'value',
			'key' => 'field_5887792582cf1',
			'label' => '3. Batters Boxes?',
			'name' => 'marco_home_plate_batters_boxes',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'post_type' => array (
				0 => 'materials',
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'object',
			'ui' => 1,
			'key' => 'field_58877ca925b3b',
			'label' => 'Select the finishing layer material for the Batters Boxes.',
			'name' => 'marco_home_plate_select_the_finishing_layer_material_for_the_batters_boxes',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_5887792582cf1',
						'operator' => '==',
						'value' => '3_x_5',
					),
				),
				array (
					array (
						'field' => 'field_5887792582cf1',
						'operator' => '==',
						'value' => '4_x_6',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'layout' => 'vertical',
			'choices' => array (
				'bagged' => 'Bagged',
				'in_bulk' => 'In Bulk',
			),
			'default_value' => '',
			'other_choice' => 0,
			'save_other_choice' => 0,
			'allow_null' => 0,
			'return_format' => 'value',
			'key' => 'field_58877cc625b3c',
			'label' => 'Materials Packaging Type',
			'name' => 'marco_home_plate_batters_box_materials_packaging_type',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_5887792582cf1',
						'operator' => '==',
						'value' => '3_x_5',
					),
				),
				array (
					array (
						'field' => 'field_5887792582cf1',
						'operator' => '==',
						'value' => '4_x_6',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'layout' => 'vertical',
			'choices' => array (
				'yes' => 'Yes',
				'no' => 'No',
			),
			'default_value' => '',
			'other_choice' => 0,
			'save_other_choice' => 0,
			'allow_null' => 0,
			'return_format' => 'value',
			'key' => 'field_58877d0425b3d',
			'label' => 'Use Field Bricks?',
			'name' => 'marco_home_plate_batters_box_use_field_bricks',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_5887792582cf1',
						'operator' => '==',
						'value' => '3_x_5',
					),
				),
				array (
					array (
						'field' => 'field_5887792582cf1',
						'operator' => '==',
						'value' => '4_x_6',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'layout' => 'vertical',
			'choices' => array (
				'none' => 'None',
				'3_x_5' => '3\' x 5\'',
				'4_x_6' => '4\' x 6\'',
			),
			'default_value' => '',
			'other_choice' => 0,
			'save_other_choice' => 0,
			'allow_null' => 0,
			'return_format' => 'value',
			'key' => 'field_5887813a4f360',
			'label' => '4. Catchers Box?',
			'name' => 'marco_home_plate_catcher_box',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'post_type' => array (
				0 => 'materials',
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'object',
			'ui' => 1,
			'key' => 'field_588781204f35f',
			'label' => 'Select the finishing layer material for the Catchers Box',
			'name' => 'macro_home_plate_select_the_finishing_layer_material_for_the_catchers_box',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_5887813a4f360',
						'operator' => '==',
						'value' => '3_x_5',
					),
				),
				array (
					array (
						'field' => 'field_5887813a4f360',
						'operator' => '==',
						'value' => '4_x_6',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'layout' => 'vertical',
			'choices' => array (
				'bagged' => 'Bagged',
				'in_bulk' => 'In Bulk',
			),
			'default_value' => '',
			'other_choice' => 0,
			'save_other_choice' => 0,
			'allow_null' => 0,
			'return_format' => 'value',
			'key' => 'field_588782675558e',
			'label' => 'Materials Packaging Type',
			'name' => 'marco_home_plate_catchers_box_materials_packaging_type',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_5887813a4f360',
						'operator' => '==',
						'value' => '3_x_5',
					),
				),
				array (
					array (
						'field' => 'field_5887813a4f360',
						'operator' => '==',
						'value' => '4_x_6',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'layout' => 'vertical',
			'choices' => array (
				'yes' => 'Yes',
				'no' => 'No',
			),
			'default_value' => '',
			'other_choice' => 0,
			'save_other_choice' => 0,
			'allow_null' => 0,
			'return_format' => 'value',
			'key' => 'field_588782805558f',
			'label' => 'Use Field Bricks?',
			'name' => 'marco_home_plate_catchers_box_use_field_bricks',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_5887813a4f360',
						'operator' => '==',
						'value' => '3_x_5',
					),
				),
				array (
					array (
						'field' => 'field_5887813a4f360',
						'operator' => '==',
						'value' => '4_x_6',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'post_type' => array (
				0 => 'materials',
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'object',
			'ui' => 1,
			'key' => 'field_588782c255590',
			'label' => '5. Select the base layer material for the home plate area.',
			'name' => 'marco_home_plate_select_the_base_layer_material_for_the_home_plate_area',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_5887830db01b8',
			'label' => 'Depth of Base Layer Material: (inches)',
			'name' => 'marco_home_plate_depth_of_base_layer_second_material_inches',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'placement' => 'top',
			'endpoint' => 0,
			'key' => 'field_588784442ff9b',
			'label' => 'Warning Track Area',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'post_type' => array (
				0 => 'materials',
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'object',
			'ui' => 1,
			'key' => 'field_5887844e2ff9c',
			'label' => '1. Select the material for the warning track.',
			'name' => 'marco_warning_track_select_the_material_for_the_warning_track',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'message' => '',
			'esc_html' => 0,
			'new_lines' => 'wpautop',
			'key' => 'field_588784752ff9d',
			'label' => '2. Enter the following measurements:',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_588784992ff9e',
			'label' => 'Perimeter: (feet)',
			'name' => 'marco_warning_track_perimeter_feet',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_588784b32ff9f',
			'label' => 'Width: (feet)',
			'name' => 'marco_warning_track_width_feet',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_588784c92ffa0',
			'label' => 'Depth of Warning Track Materials: (inches)',
			'name' => 'marco_warning_track_depth_of_warning_track_materials_inches',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'post_type' => array (
				0 => 'materials',
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'object',
			'ui' => 1,
			'key' => 'field_5887861e2ffa1',
			'label' => '3. Select the base layer material for the warning track.',
			'name' => 'marco_warning_track_select_the_base_layer_material_for_the_warning_track',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_588786462ffa2',
			'label' => 'Depth of Base Layer Material: (inches)',
			'name' => 'marco_warning_track_depth_of_base_layer_material_inches',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'placement' => 'top',
			'endpoint' => 0,
			'key' => 'field_588786682ffa3',
			'label' => 'Bull Pen Area',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'layout' => 'horizontal',
			'choices' => array (
				'1' => 'One Bull Pen',
				'2' => 'Two Bull Pens',
			),
			'default_value' => 'two_bull_pens',
			'other_choice' => 0,
			'save_other_choice' => 0,
			'allow_null' => 0,
			'return_format' => 'value',
			'key' => 'field_5887867c2ffa4',
			'label' => '1. Quantity',
			'name' => 'marco_bull_pen_quantity',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'post_type' => array (
				0 => 'materials',
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'object',
			'ui' => 1,
			'key' => 'field_588786e02ffa5',
			'label' => '2. Select the finishing layer material of the bull pen.',
			'name' => 'marco_bull_pen_select_the_finishing_layer_material_of_the_bull_pen',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'message' => '',
			'esc_html' => 0,
			'new_lines' => 'wpautop',
			'key' => 'field_588788c36f908',
			'label' => '3. Enter the following measurements:',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_588788db6f909',
			'label' => 'Length: (feet)',
			'name' => 'marco_bull_pen_length_feet',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_588788ea6f90a',
			'label' => 'Width: (feet)',
			'name' => 'marco_bull_pen_width_feet',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_588788ff6f90b',
			'label' => 'Depth of Materials: (inches)',
			'name' => 'marco_bull_pen_depth_of_materials_inches',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'post_type' => array (
				0 => 'materials',
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'object',
			'ui' => 1,
			'key' => 'field_5887891a6f90c',
			'label' => '4. Select the base layer material for the bull pen.',
			'name' => 'marco_bull_pen_select_the_base_layer_material_for_the_bull_pen',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_588789316f90d',
			'label' => 'Depth of Base Layer Material: (inches)',
			'name' => 'marco_bull_pen_depth_of_base_layer_material_inches',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'placement' => 'top',
			'endpoint' => 0,
			'key' => 'field_58878b83a1347',
			'label' => 'Miscellaneous Area',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_58878b90a1348',
			'label' => '1. Enter a name for this area.',
			'name' => 'marco_miscellaneous_enter_a_name_for_this_area',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'layout' => 'vertical',
			'choices' => array (
				'one_area' => 'One Area',
				'two_of_these_areas' => 'Two of these Areas',
			),
			'default_value' => '',
			'other_choice' => 0,
			'save_other_choice' => 0,
			'allow_null' => 0,
			'return_format' => 'value',
			'key' => 'field_58878ba5a1349',
			'label' => '2. Quantity',
			'name' => 'marco_miscellaneous_quantity',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'post_type' => array (
				0 => 'materials',
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'object',
			'ui' => 1,
			'key' => 'field_58878bdea134a',
			'label' => '3. Select the finishing layer material',
			'name' => 'marco_miscellaneous_select_the_finishing_layer_material',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'layout' => 'vertical',
			'choices' => array (
				'dimensions' => 'Dimensions',
				'area' => 'Area (sq. ft)',
			),
			'default_value' => '',
			'other_choice' => 0,
			'save_other_choice' => 0,
			'allow_null' => 0,
			'return_format' => 'value',
			'key' => 'field_58878c3aa695a',
			'label' => '4. Enter the following measurements:',
			'name' => 'marco_miscellaneous_enter_the_following_measurements:',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_58878c72a695b',
			'label' => 'Length: (feet)',
			'name' => 'marco_miscellaneous_length_feet',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_58878c3aa695a',
						'operator' => '==',
						'value' => 'dimensions',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_58878c98a695c',
			'label' => 'Width: (feet)',
			'name' => 'marco_miscellaneous_width_feet',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_58878c3aa695a',
						'operator' => '==',
						'value' => 'dimensions',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_58878caba695d',
			'label' => 'Area: (sq. ft)',
			'name' => 'marco_miscellaneous_area',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_58878c3aa695a',
						'operator' => '==',
						'value' => 'area',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_58878d48a695e',
			'label' => 'Depth of Materials: (inches)',
			'name' => 'marco_miscellaneous_depth_of_materials_inches',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'post_type' => array (
				0 => 'materials',
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'object',
			'ui' => 1,
			'key' => 'field_58878d61a695f',
			'label' => '5. Select the base layer material.',
			'name' => 'marco_miscellaneous_select_the_base_layer_material',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_58878d9ba6960',
			'label' => 'Depth of Base Layer Material: (inches)',
			'name' => 'marco_miscellaneous_depth_of_base_layer_material_inches',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'quotes-misc',
			)
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;
